import type {
  Bookmaker,
  CanonicalTeam,
  League,
  Match,
  OddsOffer,
  Opportunity,
  OutcomeOffer,
  EventReviewCase,
  SystemStatus,
  ScrapeSettingsResponse,
  TelegramSettingsResponse,
  TeamReviewCase,
  UnresolvedOdds,
} from './types';

const now = new Date();
const hours = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();
const ago = (min: number) => new Date(now.getTime() - min * 60000).toISOString();

export const mockLeagues: League[] = [
  { id: 'euroleague', name: 'EuroLeague', sport: 'basketball', country: null, is_active: true },
  { id: 'aba-league', name: 'ABA League', sport: 'basketball', country: 'Serbia', is_active: true },
  { id: 'kls', name: 'KLS', sport: 'basketball', country: 'Serbia', is_active: true },
  { id: 'uae_2', name: 'UAE 2', sport: 'football', country: null, is_active: true },
  { id: 'egypt_1_relegation_group', name: 'Egypt 1 - Relegation Group', sport: 'football', country: null, is_active: true },
  { id: 'spain_tercera_rfef_group_11', name: 'Spain Tercera RFEF - Group 11', sport: 'football', country: null, is_active: true },
  { id: 'atp_dubai', name: 'ATP Dubai', sport: 'tennis', country: null, is_active: true },
];

export const mockBookmakers: Bookmaker[] = [
  { id: 'mozzart', name: 'Mozzart', is_active: true },
  { id: 'meridian', name: 'Meridian', is_active: true },
  { id: 'maxbet', name: 'MaxBet', is_active: true },
  { id: 'balkanbet', name: 'BalkanBet', is_active: true },
  { id: 'oktagonbet', name: 'OktagonBet', is_active: true },
  { id: 'merkurxtip', name: 'MERKUR X TIP', is_active: true },
  { id: 'soccerbet', name: 'SoccerBet', is_active: true },
  { id: 'superbet', name: 'Superbet', is_active: true },
  { id: 'betole', name: 'BetOle', is_active: true },
  { id: '365', name: '365', is_active: true },
  { id: 'pinnbet', name: 'PinnBet', is_active: true },
  { id: 'volcanobet', name: 'VolcanoBet', is_active: true },
];

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    league_id: 'euroleague',
    league_name: 'EuroLeague',
    sport: 'basketball',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    start_time: hours(2),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'meridian', name: 'Meridian' },
      { id: 'mozzart', name: 'Mozzart' },
      { id: 'betole', name: 'BetOle' },
      { id: '365', name: '365' },
      { id: 'volcanobet', name: 'VolcanoBet' },
    ],
  },
  {
    id: 'match-2',
    league_id: 'euroleague',
    league_name: 'EuroLeague',
    sport: 'basketball',
    home_team: 'Fenerbahce',
    away_team: 'Partizan',
    start_time: hours(3),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'meridian', name: 'Meridian' },
      { id: 'mozzart', name: 'Mozzart' },
      { id: 'betole', name: 'BetOle' },
      { id: '365', name: '365' },
      { id: 'volcanobet', name: 'VolcanoBet' },
    ],
  },
  {
    id: 'match-3',
    league_id: 'euroleague',
    league_name: 'EuroLeague',
    sport: 'basketball',
    home_team: 'Barcelona',
    away_team: 'Crvena Zvezda',
    start_time: hours(5),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'meridian', name: 'Meridian' },
      { id: 'mozzart', name: 'Mozzart' },
    ],
  },
  {
    id: 'match-4',
    league_id: 'aba-league',
    league_name: 'ABA League',
    sport: 'basketball',
    home_team: 'Mega MIS',
    away_team: 'Budućnost',
    start_time: hours(1),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'mozzart', name: 'Mozzart' },
    ],
  },
  {
    id: 'match-5',
    league_id: 'aba-league',
    league_name: 'ABA League',
    sport: 'basketball',
    home_team: 'Crvena Zvezda',
    away_team: 'Cedevita Olimpija',
    start_time: hours(4),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'meridian', name: 'Meridian' },
      { id: 'mozzart', name: 'Mozzart' },
    ],
  },
  {
    id: 'match-6',
    league_id: 'kls',
    league_name: 'KLS',
    sport: 'basketball',
    home_team: 'FMP',
    away_team: 'Vojvodina',
    start_time: hours(1.5),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'meridian', name: 'Meridian' },
      { id: 'mozzart', name: 'Mozzart' },
    ],
  },
  {
    id: 'football-match-1',
    league_id: 'uae_2',
    league_name: 'UAE 2',
    sport: 'football',
    home_team: 'Hatta SC',
    away_team: 'Al Urooba UAE',
    start_time: hours(2.25),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'mozzart', name: 'Mozzart' },
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'balkanbet', name: 'BalkanBet' },
      { id: 'oktagonbet', name: 'OktagonBet' },
      { id: 'soccerbet', name: 'SoccerBet' },
      { id: 'merkurxtip', name: 'MERKUR X TIP' },
      { id: 'betole', name: 'BetOle' },
      { id: '365', name: '365' },
      { id: 'superbet', name: 'Superbet' },
      { id: 'admiralbet', name: 'AdmiralBet' },
      { id: 'pinnbet', name: 'PinnBet' },
      { id: 'volcanobet', name: 'VolcanoBet' },
    ],
  },
  {
    id: 'football-match-2',
    league_id: 'egypt_1_relegation_group',
    league_name: 'Egypt 1 - Relegation Group',
    sport: 'football',
    home_team: 'El Gouna FC',
    away_team: 'Haras El Hodood',
    start_time: hours(2.5),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'mozzart', name: 'Mozzart' },
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'balkanbet', name: 'BalkanBet' },
      { id: 'oktagonbet', name: 'OktagonBet' },
      { id: 'soccerbet', name: 'SoccerBet' },
      { id: 'merkurxtip', name: 'MERKUR X TIP' },
      { id: 'betole', name: 'BetOle' },
      { id: '365', name: '365' },
      { id: 'superbet', name: 'Superbet' },
      { id: 'admiralbet', name: 'AdmiralBet' },
      { id: 'pinnbet', name: 'PinnBet' },
      { id: 'volcanobet', name: 'VolcanoBet' },
    ],
  },
  {
    id: 'football-match-3',
    league_id: 'spain_tercera_rfef_group_11',
    league_name: 'Spain Tercera RFEF - Group 11',
    sport: 'football',
    home_team: 'CD Llosetense',
    away_team: 'CE Mercadal',
    start_time: hours(3),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'balkanbet', name: 'BalkanBet' },
    ],
  },
  {
    id: 'tennis-match-1',
    league_id: 'atp_dubai',
    league_name: 'ATP Dubai',
    sport: 'tennis',
    home_team: 'Novak Djokovic',
    away_team: 'Carlos Alcaraz',
    start_time: hours(4.5),
    status: 'upcoming',
    available_bookmakers: [
      { id: 'maxbet', name: 'MaxBet' },
      { id: 'balkanbet', name: 'BalkanBet' },
    ],
  },
];

export const mockFootballOutcomeOffers: OutcomeOffer[] = [
  { id: 1001, match_id: 'football-match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_result', outcome_code: 'home', odds: 2.5, line: null, raw_label: '1', scraped_at: ago(4) },
  { id: 1002, match_id: 'football-match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_result', outcome_code: 'draw', odds: 3.15, line: null, raw_label: 'X', scraped_at: ago(4) },
  { id: 1003, match_id: 'football-match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_result', outcome_code: 'away', odds: 2.55, line: null, raw_label: '2', scraped_at: ago(4) },
  { id: 1004, match_id: 'football-match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.42, line: null, raw_label: '1X', scraped_at: ago(4) },
  { id: 1005, match_id: 'football-match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.42, line: null, raw_label: 'X2', scraped_at: ago(4) },
  { id: 1006, match_id: 'football-match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.12, line: 2.5, raw_label: '0-2', scraped_at: ago(4) },
  { id: 1007, match_id: 'football-match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.73, line: 2.5, raw_label: '3+', scraped_at: ago(4) },
  { id: 1008, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_result', outcome_code: 'home', odds: 2.4, line: null, raw_label: '1', scraped_at: ago(3) },
  { id: 1009, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_result', outcome_code: 'draw', odds: 3.2, line: null, raw_label: 'X', scraped_at: ago(3) },
  { id: 1010, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_result', outcome_code: 'away', odds: 2.55, line: null, raw_label: '2', scraped_at: ago(3) },
  { id: 1011, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.37, line: null, raw_label: '1X', scraped_at: ago(3) },
  { id: 1012, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.24, line: null, raw_label: '12', scraped_at: ago(3) },
  { id: 1013, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.42, line: null, raw_label: 'X2', scraped_at: ago(3) },
  { id: 1014, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.78, line: 2.5, raw_label: '0-2', scraped_at: ago(3) },
  { id: 1015, match_id: 'football-match-1', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.82, line: 2.5, raw_label: '3+', scraped_at: ago(3) },
  { id: 1016, match_id: 'football-match-2', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_result', outcome_code: 'home', odds: 2.3, line: null, raw_label: '1', scraped_at: ago(5) },
  { id: 1017, match_id: 'football-match-2', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.53, line: null, raw_label: 'X2', scraped_at: ago(4) },
  { id: 1018, match_id: 'football-match-2', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.15, line: 2.5, raw_label: '0-2', scraped_at: ago(5) },
  { id: 1019, match_id: 'football-match-2', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.85, line: 2.5, raw_label: '3+', scraped_at: ago(4) },
  { id: 1020, match_id: 'football-match-3', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_result', outcome_code: 'home', odds: 1.58, line: null, raw_label: '1', scraped_at: ago(5) },
  { id: 1021, match_id: 'football-match-3', bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.71, line: 2.5, raw_label: '0-2', scraped_at: ago(4) },
  { id: 1022, match_id: 'football-match-3', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.9, line: 2.5, raw_label: '3+', scraped_at: ago(5) },
  { id: 1023, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_result', outcome_code: 'home', odds: 2.45, line: null, raw_label: '1', scraped_at: ago(2) },
  { id: 1024, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_result', outcome_code: 'draw', odds: 3.1, line: null, raw_label: 'X', scraped_at: ago(2) },
  { id: 1025, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_result', outcome_code: 'away', odds: 2.7, line: null, raw_label: '2', scraped_at: ago(2) },
  { id: 1026, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.4, line: null, raw_label: '1X', scraped_at: ago(2) },
  { id: 1027, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.28, line: null, raw_label: '12', scraped_at: ago(2) },
  { id: 1028, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.48, line: null, raw_label: 'X2', scraped_at: ago(2) },
  { id: 1029, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.05, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1030, match_id: 'football-match-1', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.85, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
  { id: 1031, match_id: 'football-match-2', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.74, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1032, match_id: 'football-match-2', bookmaker_id: 'soccerbet', bookmaker_name: 'SoccerBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.2, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
  { id: 1033, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_result', outcome_code: 'home', odds: 2.32, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1034, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_result', outcome_code: 'draw', odds: 3.25, line: null, raw_label: 'X', scraped_at: ago(1) },
  { id: 1035, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_result', outcome_code: 'away', odds: 2.68, line: null, raw_label: '2', scraped_at: ago(1) },
  { id: 1036, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.36, line: null, raw_label: '1X', scraped_at: ago(1) },
  { id: 1037, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.27, line: null, raw_label: '12', scraped_at: ago(1) },
  { id: 1038, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.5, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1039, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_total_goals', outcome_code: 'under', odds: 2, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1040, match_id: 'football-match-1', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.88, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1041, match_id: 'football-match-2', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.8, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1042, match_id: 'football-match-2', bookmaker_id: 'merkurxtip', bookmaker_name: 'MERKUR X TIP', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.1, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1043, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_result', outcome_code: 'home', odds: 2.36, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1044, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_result', outcome_code: 'draw', odds: 3.18, line: null, raw_label: 'X', scraped_at: ago(1) },
  { id: 1045, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_result', outcome_code: 'away', odds: 2.62, line: null, raw_label: '2', scraped_at: ago(1) },
  { id: 1046, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.38, line: null, raw_label: '1X', scraped_at: ago(1) },
  { id: 1047, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.25, line: null, raw_label: '12', scraped_at: ago(1) },
  { id: 1048, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.47, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1049, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.03, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1050, match_id: 'football-match-1', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.84, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1051, match_id: 'football-match-2', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.76, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1052, match_id: 'football-match-2', bookmaker_id: 'oktagonbet', bookmaker_name: 'OktagonBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.18, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1053, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_result', outcome_code: 'home', odds: 2.42, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1054, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_result', outcome_code: 'draw', odds: 3.22, line: null, raw_label: 'X', scraped_at: ago(1) },
  { id: 1055, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_result', outcome_code: 'away', odds: 2.58, line: null, raw_label: '2', scraped_at: ago(1) },
  { id: 1056, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.39, line: null, raw_label: '1X', scraped_at: ago(1) },
  { id: 1057, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.26, line: null, raw_label: '12', scraped_at: ago(1) },
  { id: 1058, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.45, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1059, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.06, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1060, match_id: 'football-match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.83, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1061, match_id: 'football-match-2', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.51, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1062, match_id: 'football-match-2', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.78, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1063, match_id: 'football-match-2', bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.16, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1064, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_result', outcome_code: 'home', odds: 2.38, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1065, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_result', outcome_code: 'draw', odds: 3.20, line: null, raw_label: 'X', scraped_at: ago(1) },
  { id: 1066, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_result', outcome_code: 'away', odds: 2.60, line: null, raw_label: '2', scraped_at: ago(1) },
  { id: 1067, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.40, line: null, raw_label: '1X', scraped_at: ago(1) },
  { id: 1068, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.27, line: null, raw_label: '12', scraped_at: ago(1) },
  { id: 1069, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.46, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1070, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.04, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1071, match_id: 'football-match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.85, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1072, match_id: 'football-match-2', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.49, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1073, match_id: 'football-match-2', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.74, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1074, match_id: 'football-match-2', bookmaker_id: '365', bookmaker_name: '365', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.20, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1075, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_result', outcome_code: 'home', odds: 2.40, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1076, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_result', outcome_code: 'draw', odds: 3.25, line: null, raw_label: 'X', scraped_at: ago(1) },
  { id: 1077, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_result', outcome_code: 'away', odds: 2.55, line: null, raw_label: '2', scraped_at: ago(1) },
  { id: 1078, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.39, line: null, raw_label: '1X', scraped_at: ago(1) },
  { id: 1079, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.26, line: null, raw_label: '12', scraped_at: ago(1) },
  { id: 1080, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.45, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1081, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.05, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1082, match_id: 'football-match-1', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.84, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1083, match_id: 'football-match-2', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_result', outcome_code: 'home', odds: 1.92, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1084, match_id: 'football-match-2', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.78, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1085, match_id: 'football-match-2', bookmaker_id: 'superbet', bookmaker_name: 'Superbet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.16, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1086, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_result', outcome_code: 'home', odds: 2.42, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1087, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_result', outcome_code: 'draw', odds: 3.20, line: null, raw_label: 'X', scraped_at: ago(1) },
  { id: 1088, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_result', outcome_code: 'away', odds: 2.60, line: null, raw_label: '2', scraped_at: ago(1) },
  { id: 1089, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.40, line: null, raw_label: '1X', scraped_at: ago(1) },
  { id: 1090, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.27, line: null, raw_label: '12', scraped_at: ago(1) },
  { id: 1091, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.46, line: null, raw_label: 'X2', scraped_at: ago(1) },
  { id: 1092, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.10, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1093, match_id: 'football-match-1', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.80, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  { id: 1094, match_id: 'football-match-2', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_result', outcome_code: 'home', odds: 1.94, line: null, raw_label: '1', scraped_at: ago(1) },
  { id: 1095, match_id: 'football-match-2', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.80, line: 2.5, raw_label: '0-2', scraped_at: ago(1) },
  { id: 1096, match_id: 'football-match-2', bookmaker_id: 'admiralbet', bookmaker_name: 'AdmiralBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.12, line: 2.5, raw_label: '3+', scraped_at: ago(1) },
  // PinnBet — partial-mode shape: result + 2.5 totals on game 0, partial on game 1.  No double chance (default mode).
  { id: 1097, match_id: 'football-match-1', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_result', outcome_code: 'home', odds: 2.45, line: null, raw_label: '1', scraped_at: ago(2) },
  { id: 1098, match_id: 'football-match-1', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_result', outcome_code: 'draw', odds: 3.18, line: null, raw_label: 'X', scraped_at: ago(2) },
  { id: 1099, match_id: 'football-match-1', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_result', outcome_code: 'away', odds: 2.62, line: null, raw_label: '2', scraped_at: ago(2) },
  { id: 1100, match_id: 'football-match-1', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.08, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1101, match_id: 'football-match-1', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.82, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
  { id: 1102, match_id: 'football-match-2', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_result', outcome_code: 'home', odds: 1.96, line: null, raw_label: '1', scraped_at: ago(2) },
  { id: 1103, match_id: 'football-match-2', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.82, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1104, match_id: 'football-match-2', bookmaker_id: 'pinnbet', bookmaker_name: 'PinnBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.14, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
  // Mozzart — list-only football shape: result + double chance + 2.5 totals from betting/matches.
  { id: 1105, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_result', outcome_code: 'home', odds: 2.48, line: null, raw_label: '1', scraped_at: ago(2) },
  { id: 1106, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_result', outcome_code: 'draw', odds: 3.18, line: null, raw_label: 'X', scraped_at: ago(2) },
  { id: 1107, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_result', outcome_code: 'away', odds: 2.62, line: null, raw_label: '2', scraped_at: ago(2) },
  { id: 1108, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.41, line: null, raw_label: '1X', scraped_at: ago(2) },
  { id: 1109, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.29, line: null, raw_label: '12', scraped_at: ago(2) },
  { id: 1110, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.47, line: null, raw_label: 'X2', scraped_at: ago(2) },
  { id: 1111, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.80, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1112, match_id: 'football-match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.90, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
  { id: 1113, match_id: 'football-match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_result', outcome_code: 'home', odds: 1.98, line: null, raw_label: '1', scraped_at: ago(2) },
  { id: 1114, match_id: 'football-match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.76, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1115, match_id: 'football-match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.18, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
  // VolcanoBet — Xtreme batched event-market shape: result + double chance + 2.5 totals.
  { id: 1116, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_result', outcome_code: 'home', odds: 2.46, line: null, raw_label: '1', scraped_at: ago(2) },
  { id: 1117, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_result', outcome_code: 'draw', odds: 3.16, line: null, raw_label: 'X', scraped_at: ago(2) },
  { id: 1118, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_result', outcome_code: 'away', odds: 2.64, line: null, raw_label: '2', scraped_at: ago(2) },
  { id: 1119, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_double_chance', outcome_code: 'home_or_draw', odds: 1.42, line: null, raw_label: '1X', scraped_at: ago(2) },
  { id: 1120, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_double_chance', outcome_code: 'home_or_away', odds: 1.28, line: null, raw_label: '12', scraped_at: ago(2) },
  { id: 1121, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.46, line: null, raw_label: 'X2', scraped_at: ago(2) },
  { id: 1122, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.88, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1123, match_id: 'football-match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 1.92, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
  { id: 1124, match_id: 'football-match-2', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_result', outcome_code: 'home', odds: 2.02, line: null, raw_label: '1', scraped_at: ago(2) },
  { id: 1125, match_id: 'football-match-2', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 1.82, line: 2.5, raw_label: '0-2', scraped_at: ago(2) },
  { id: 1126, match_id: 'football-match-2', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.12, line: 2.5, raw_label: '3+', scraped_at: ago(2) },
];

export const mockMatchOutcomeOfferScopes: Record<string, string[]> = {
  'football-match-1': ['football-match-1'],
  'football-match-2': ['football-match-2'],
  'football-match-3': ['football-match-3'],
};

export const mockOpportunities: Opportunity[] = [
  {
    id: 2001,
    sport: 'basketball',
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    start_time: hours(2),
    opportunity_type: 'middle',
    market_type: 'player_points',
    subject_type: 'player',
    subject_key: 'player:sasha-vezenkov',
    subject_name: 'Sasha Vezenkov',
    line: null,
    profit_margin: -0.0125,
    middle_profit_margin: 0.8421,
    middle_hit_probability: 0.312,
    middle_ev: 0.254,
    middle_model_confidence: 'medium',
    middle_model_diagnostics: { mode: 'fitted', model_family: 'normal', consensus_points: 4 },
    middle_ev_rank: 0.2159,
    market_keys: ['mock-player-points-sasha-18.5', 'mock-player-points-sasha-20.5'],
    legs: [
      { bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', outcome_code: 'over', odds: 1.85, line: 18.5, raw_label: '18.5+' },
      { bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', outcome_code: 'under', odds: 1.9, line: 20.5, raw_label: '20.5-' },
    ],
    detected_at: ago(3),
    is_active: true,
  },
  {
    id: 2002,
    sport: 'basketball',
    match_id: 'match-2',
    home_team: 'Fenerbahce',
    away_team: 'Partizan',
    league_name: 'EuroLeague',
    start_time: hours(3),
    opportunity_type: 'same_line_arbitrage',
    market_type: 'player_points',
    subject_type: 'player',
    subject_key: 'player:nigel-hayes-davis',
    subject_name: 'Nigel Hayes-Davis',
    line: 16.5,
    profit_margin: 0.0351,
    middle_profit_margin: null,
    middle_hit_probability: null,
    middle_ev: null,
    middle_model_confidence: null,
    middle_model_diagnostics: {},
    middle_ev_rank: null,
    market_keys: ['mock-player-points-nigel-16.5'],
    legs: [
      { bookmaker_id: 'betole', bookmaker_name: 'BetOle', market_type: 'player_points', outcome_code: 'over', odds: 2.08, line: 16.5, raw_label: '16.5+' },
      { bookmaker_id: '365', bookmaker_name: '365', market_type: 'player_points', outcome_code: 'under', odds: 2.05, line: 16.5, raw_label: '16.5-' },
    ],
    detected_at: ago(2),
    is_active: true,
  },
  {
    id: 2003,
    sport: 'basketball',
    match_id: 'match-6',
    home_team: 'FMP',
    away_team: 'Vojvodina',
    league_name: 'KLS',
    start_time: hours(1.5),
    opportunity_type: 'middle',
    market_type: 'game_total_ot',
    subject_type: 'event',
    subject_key: 'event',
    subject_name: null,
    line: null,
    profit_margin: -0.021,
    middle_profit_margin: 0.7667,
    middle_hit_probability: 0.118,
    middle_ev: 0.0719,
    middle_model_confidence: 'low',
    middle_model_diagnostics: { mode: 'fitted', model_family: 'normal', consensus_points: 2 },
    middle_ev_rank: 0.0467,
    market_keys: ['mock-game-total-fmp-158.5', 'mock-game-total-fmp-161.5'],
    legs: [
      { bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total_ot', outcome_code: 'over', odds: 1.88, line: 158.5, raw_label: '158.5+' },
      { bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total_ot', outcome_code: 'under', odds: 1.95, line: 161.5, raw_label: '161.5-' },
    ],
    detected_at: ago(4),
    is_active: true,
  },
  {
    id: 2004,
    sport: 'football',
    match_id: 'football-match-2',
    home_team: 'El Gouna FC',
    away_team: 'Haras El Hodood',
    league_name: 'Egypt 1 - Relegation Group',
    start_time: hours(2.5),
    opportunity_type: 'same_line_arbitrage',
    market_type: 'football_total_goals',
    subject_type: 'event',
    line: 2.5,
    profit_margin: 0.1277,
    middle_profit_margin: null,
    middle_hit_probability: null,
    middle_ev: null,
    middle_model_confidence: null,
    middle_model_diagnostics: {},
    middle_ev_rank: null,
    market_keys: ['mock-football-total-2.5'],
    legs: [
      { bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_total_goals', outcome_code: 'under', odds: 2.15, line: 2.5, raw_label: '0-2' },
      { bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_total_goals', outcome_code: 'over', odds: 2.85, line: 2.5, raw_label: '3+' },
    ],
    detected_at: ago(4),
    is_active: true,
  },
  {
    id: 2005,
    sport: 'football',
    match_id: 'football-match-1',
    home_team: 'Hatta SC',
    away_team: 'Al Urooba UAE',
    league_name: 'UAE 2',
    start_time: hours(2.25),
    opportunity_type: 'complementary_outcomes',
    market_type: 'football_result_double_chance',
    subject_type: 'event',
    line: null,
    profit_margin: 0.0253,
    middle_profit_margin: null,
    middle_hit_probability: null,
    middle_ev: null,
    middle_model_confidence: null,
    middle_model_diagnostics: {},
    middle_ev_rank: null,
    market_keys: ['mock-football-result-home', 'mock-football-double-chance-draw-away'],
    legs: [
      { bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'football_result', outcome_code: 'home', odds: 2.5, line: null, raw_label: '1' },
      { bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'football_double_chance', outcome_code: 'draw_or_away', odds: 1.42, line: null, raw_label: 'X2' },
    ],
    detected_at: ago(3),
    is_active: true,
  },
  {
    id: 2006,
    sport: 'tennis',
    match_id: 'tennis-match-1',
    home_team: 'Novak Djokovic',
    away_team: 'Carlos Alcaraz',
    league_name: 'ATP Dubai',
    start_time: hours(4.5),
    opportunity_type: 'same_line_arbitrage',
    market_type: 'match_winner',
    subject_type: 'event',
    subject_key: 'event',
    subject_name: null,
    line: null,
    profit_margin: 0.0317,
    middle_profit_margin: null,
    middle_hit_probability: null,
    middle_ev: null,
    middle_model_confidence: null,
    middle_model_diagnostics: {},
    middle_ev_rank: null,
    market_keys: ['mock-tennis-match-winner'],
    legs: [
      { bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'match_winner', outcome_code: 'home', odds: 2.15, line: null, raw_label: '1' },
      { bookmaker_id: 'balkanbet', bookmaker_name: 'BalkanBet', market_type: 'match_winner', outcome_code: 'away', odds: 2.05, line: null, raw_label: '2' },
    ],
    detected_at: ago(2),
    is_active: true,
  },
];

export const mockOddsOffers: OddsOffer[] = [
  // Match 1: Olympiacos vs Real Madrid
  { id: 1, match_id: 'match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 18.5, over_odds: 1.85, under_odds: 1.95, scraped_at: ago(5) },
  { id: 2, match_id: 'match-1', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 20.5, over_odds: 1.75, under_odds: 1.90, scraped_at: ago(3) },
  { id: 3, match_id: 'match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23281441', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 19.5, over_odds: 1.80, under_odds: 1.88, scraped_at: ago(4) },
  { id: 4, match_id: 'match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 155.5, over_odds: 1.80, under_odds: 2.00, scraped_at: ago(5) },
  { id: 5, match_id: 'match-1', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total', player_name: null, threshold: 158.5, over_odds: 1.90, under_odds: 1.85, scraped_at: ago(3) },
  { id: 6, match_id: 'match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23281441', market_type: 'game_total', player_name: null, threshold: 156.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(4) },
  { id: 7, match_id: 'match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Facundo Campazzo', threshold: 14.5, over_odds: 1.90, under_odds: 1.88, scraped_at: ago(5) },
  { id: 8, match_id: 'match-1', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Facundo Campazzo', threshold: 15.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(3) },

  // Match 2: Fenerbahce vs Partizan
  { id: 9, match_id: 'match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 15.5, over_odds: 1.88, under_odds: 1.92, scraped_at: ago(5) },
  { id: 10, match_id: 'match-2', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23289963', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 17.5, over_odds: 1.75, under_odds: 2.05, scraped_at: ago(4) },
  { id: 11, match_id: 'match-2', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 16.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(3) },
  { id: 12, match_id: 'match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 160.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(5) },
  { id: 13, match_id: 'match-2', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23289963', market_type: 'game_total', player_name: null, threshold: 162.5, over_odds: 1.88, under_odds: 1.90, scraped_at: ago(4) },

  // Match 3: Barcelona vs Crvena Zvezda
  { id: 14, match_id: 'match-3', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Nikola Kalinić', threshold: 12.5, over_odds: 1.92, under_odds: 1.85, scraped_at: ago(6) },
  { id: 15, match_id: 'match-3', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Nikola Kalinić', threshold: 14.5, over_odds: 1.78, under_odds: 2.00, scraped_at: ago(2) },
  { id: 16, match_id: 'match-3', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23290818', market_type: 'player_points', player_name: 'Nikola Kalinić', threshold: 13.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(4) },
  { id: 17, match_id: 'match-3', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 162.5, over_odds: 1.78, under_odds: 2.02, scraped_at: ago(6) },
  { id: 18, match_id: 'match-3', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total', player_name: null, threshold: 164.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(2) },

  // Match 4: Mega MIS vs Budućnost
  { id: 19, match_id: 'match-4', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Nikola Đurišić', threshold: 16.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(8) },
  { id: 20, match_id: 'match-4', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23290818', market_type: 'player_points', player_name: 'Nikola Đurišić', threshold: 18.5, over_odds: 1.78, under_odds: 2.00, scraped_at: ago(6) },
  { id: 21, match_id: 'match-4', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 165.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(8) },
  { id: 22, match_id: 'match-4', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23290818', market_type: 'game_total', player_name: null, threshold: 168.5, over_odds: 1.90, under_odds: 1.88, scraped_at: ago(6) },

  // Match 5: Crvena Zvezda vs Cedevita Olimpija
  { id: 23, match_id: 'match-5', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Filip Petrušev', threshold: 17.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(10) },
  { id: 24, match_id: 'match-5', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Filip Petrušev', threshold: 19.5, over_odds: 1.75, under_odds: 2.05, scraped_at: ago(7) },
  { id: 25, match_id: 'match-5', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23289963', market_type: 'player_points', player_name: 'Filip Petrušev', threshold: 18.5, over_odds: 1.80, under_odds: 1.98, scraped_at: ago(5) },

  // Match 6: FMP vs Vojvodina
  { id: 26, match_id: 'match-6', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 158.5, over_odds: 1.88, under_odds: 1.90, scraped_at: ago(12) },
  { id: 27, match_id: 'match-6', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total', player_name: null, threshold: 161.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(8) },
  { id: 28, match_id: 'match-6', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23281441', market_type: 'game_total_ot', player_name: null, threshold: 160.5, over_odds: 2.02, under_odds: 1.84, scraped_at: ago(6) },
  { id: 29, match_id: 'match-6', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total_ot', player_name: null, threshold: 163.5, over_odds: 1.86, under_odds: 2.02, scraped_at: ago(5) },
  { id: 30, match_id: 'match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', source_url: 'https://www.betole.com/match-special/90241113', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 19.5, over_odds: 1.84, under_odds: 1.94, scraped_at: ago(2) },
  { id: 31, match_id: 'match-1', bookmaker_id: 'betole', bookmaker_name: 'BetOle', source_url: 'https://www.betole.com/match-special/90241113', market_type: 'game_total_ot', player_name: null, threshold: 156.5, over_odds: 1.91, under_odds: 1.86, scraped_at: ago(2) },
  { id: 32, match_id: 'match-2', bookmaker_id: 'betole', bookmaker_name: 'BetOle', source_url: 'https://www.betole.com/match-special/90241114', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 16.5, over_odds: 1.84, under_odds: 1.94, scraped_at: ago(1) },
  { id: 33, match_id: 'match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 19.5, over_odds: 1.86, under_odds: 1.92, scraped_at: ago(1) },
  { id: 34, match_id: 'match-1', bookmaker_id: '365', bookmaker_name: '365', market_type: 'game_total_ot', player_name: null, threshold: 157.5, over_odds: 1.89, under_odds: 1.87, scraped_at: ago(1) },
  { id: 35, match_id: 'match-2', bookmaker_id: '365', bookmaker_name: '365', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 16.5, over_odds: 1.83, under_odds: 1.95, scraped_at: ago(1) },
  { id: 36, match_id: 'match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', source_url: 'https://www.volcanobet.rs/sport-v2/prematch/events', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 19.0, over_odds: 1.86, under_odds: 1.92, scraped_at: ago(2) },
  { id: 37, match_id: 'match-1', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', source_url: 'https://www.volcanobet.rs/sport-v2/prematch/events', market_type: 'game_total_ot', player_name: null, threshold: 157.5, over_odds: 1.89, under_odds: 1.88, scraped_at: ago(2) },
  { id: 38, match_id: 'match-2', bookmaker_id: 'volcanobet', bookmaker_name: 'VolcanoBet', source_url: 'https://www.volcanobet.rs/sport-v2/prematch/events', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 16.0, over_odds: 1.87, under_odds: 1.91, scraped_at: ago(1) },
  // Asian handicap (with OT) — Olympiacos heavy home favourite, books disagree on margin.
  // mozzart: threshold +5.5 means home favoured by 5.5 → Asian "Home -5.5"
  { id: 39, match_id: 'match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'home_handicap_ot', player_name: null, threshold: 5.5, over_odds: 1.92, under_odds: 1.88, scraped_at: ago(3) },
  // meridian disagrees: home favoured by only 3.5 → "Home -3.5" — gap with mozzart produces a middle window
  { id: 40, match_id: 'match-1', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'home_handicap_ot', player_name: null, threshold: 3.5, over_odds: 1.85, under_odds: 1.95, scraped_at: ago(2) },
  // maxbet — same line as mozzart, slightly different odds
  { id: 41, match_id: 'match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23281441', market_type: 'home_handicap_ot', player_name: null, threshold: 5.5, over_odds: 1.95, under_odds: 1.85, scraped_at: ago(2) },
  // Match 2: Fenerbahce slight underdog at home, threshold negative
  { id: 42, match_id: 'match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'home_handicap_ot', player_name: null, threshold: -1.5, over_odds: 1.90, under_odds: 1.90, scraped_at: ago(4) },
  { id: 43, match_id: 'match-2', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'home_handicap_ot', player_name: null, threshold: -2.5, over_odds: 1.92, under_odds: 1.88, scraped_at: ago(3) },
];

export const mockLegacyDiscrepancies = [
  {
    id: 1,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Sasha Vezenkov',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 18.5,
    threshold_b: 20.5,
    odds_a: 1.85,
    odds_b: 1.90,
    gap: 2.0,
    profit_margin: 0.032,
    middle_profit_margin: 0.8747,
    detected_at: ago(5),
    is_active: true,
  },
  // Extra Sasha Vezenkov player_points lines so the dashboard can demo the
  // per-(match, market, player) ladder collapse — same group key as id=1.
  {
    id: 9001,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Sasha Vezenkov',
    bookmaker_a_id: 'maxbet',
    bookmaker_a_name: 'MaxBet',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 19.5,
    threshold_b: 20.5,
    odds_a: 1.80,
    odds_b: 1.90,
    gap: 1.0,
    profit_margin: 0.024,
    middle_profit_margin: 0.7892,
    detected_at: ago(4),
    is_active: true,
  },
  {
    id: 9002,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Sasha Vezenkov',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'maxbet',
    bookmaker_b_name: 'MaxBet',
    threshold_a: 18.5,
    threshold_b: 19.5,
    odds_a: 1.85,
    odds_b: 1.88,
    gap: 1.0,
    profit_margin: 0.018,
    middle_profit_margin: 0.7411,
    detected_at: ago(5),
    is_active: true,
  },
  {
    id: 9003,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Sasha Vezenkov',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 18.5,
    threshold_b: 18.5,
    odds_a: 1.85,
    odds_b: 1.95,
    gap: 0.0,
    profit_margin: 0.011,
    detected_at: ago(5),
    is_active: true,
  },
  {
    id: 2,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'maxbet',
    bookmaker_a_name: 'MaxBet',
    bookmaker_a_source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23281441',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 155.5,
    threshold_b: 158.5,
    odds_a: 1.80,
    odds_b: 1.85,
    gap: 3.0,
    profit_margin: 0.028,
    middle_profit_margin: 0.8247,
    detected_at: ago(4),
    is_active: true,
  },
  {
    id: 3,
    match_id: 'match-2',
    home_team: 'Fenerbahce',
    away_team: 'Partizan',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Nigel Hayes-Davis',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'maxbet',
    bookmaker_b_name: 'MaxBet',
    bookmaker_b_source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23289963',
    threshold_a: 15.5,
    threshold_b: 17.5,
    odds_a: 1.88,
    odds_b: 2.05,
    gap: 2.0,
    profit_margin: 0.041,
    middle_profit_margin: 0.9613,
    detected_at: ago(5),
    is_active: true,
  },
  {
    id: 4,
    match_id: 'match-3',
    home_team: 'Barcelona',
    away_team: 'Crvena Zvezda',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Nikola Kalinić',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 12.5,
    threshold_b: 14.5,
    odds_a: 1.92,
    odds_b: 2.00,
    gap: 2.0,
    profit_margin: 0.035,
    middle_profit_margin: 0.9592,
    detected_at: ago(6),
    is_active: true,
  },
  {
    id: 5,
    match_id: 'match-4',
    home_team: 'Mega MIS',
    away_team: 'Budućnost',
    league_name: 'ABA League',
    market_type: 'player_points',
    player_name: 'Nikola Đurišić',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'maxbet',
    bookmaker_b_name: 'MaxBet',
    bookmaker_b_source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23290818',
    threshold_a: 16.5,
    threshold_b: 18.5,
    odds_a: 1.85,
    odds_b: 2.00,
    gap: 2.0,
    profit_margin: 0.024,
    middle_profit_margin: 0.9221,
    detected_at: ago(8),
    is_active: true,
  },
  {
    id: 6,
    match_id: 'match-4',
    home_team: 'Mega MIS',
    away_team: 'Budućnost',
    league_name: 'ABA League',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'maxbet',
    bookmaker_b_name: 'MaxBet',
    bookmaker_b_source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23289963',
    threshold_a: 165.5,
    threshold_b: 168.5,
    odds_a: 1.85,
    odds_b: 1.88,
    gap: 3.0,
    profit_margin: 0.018,
    middle_profit_margin: 0.8649,
    detected_at: ago(8),
    is_active: true,
  },
  {
    id: 7,
    match_id: 'match-5',
    home_team: 'Crvena Zvezda',
    away_team: 'Cedevita Olimpija',
    league_name: 'ABA League',
    market_type: 'player_points',
    player_name: 'Filip Petrušev',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 17.5,
    threshold_b: 19.5,
    odds_a: 1.82,
    odds_b: 2.05,
    gap: 2.0,
    profit_margin: 0.038,
    middle_profit_margin: 0.9282,
    detected_at: ago(7),
    is_active: true,
  },
  {
    id: 8,
    match_id: 'match-6',
    home_team: 'FMP',
    away_team: 'Vojvodina',
    league_name: 'KLS',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 158.5,
    threshold_b: 161.5,
    odds_a: 1.88,
    odds_b: 1.95,
    gap: 3.0,
    profit_margin: 0.012,
    middle_profit_margin: 0.8474,
    detected_at: ago(12),
    is_active: true,
  },
  {
    id: 9,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Facundo Campazzo',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 14.5,
    threshold_b: 15.5,
    odds_a: 1.90,
    odds_b: 1.95,
    gap: 1.0,
    profit_margin: 0.016,
    middle_profit_margin: 0.9247,
    detected_at: ago(5),
    is_active: true,
  },
  {
    id: 10,
    match_id: 'match-3',
    home_team: 'Barcelona',
    away_team: 'Crvena Zvezda',
    league_name: 'EuroLeague',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 162.5,
    threshold_b: 164.5,
    odds_a: 1.78,
    odds_b: 1.92,
    gap: 2.0,
    profit_margin: 0.021,
    middle_profit_margin: 0.9144,
    detected_at: ago(6),
    is_active: true,
  },
  {
    id: 11,
    match_id: 'match-6',
    home_team: 'FMP',
    away_team: 'Vojvodina',
    league_name: 'KLS',
    market_type: 'game_total_ot',
    player_name: null,
    bookmaker_a_id: 'maxbet',
    bookmaker_a_name: 'MaxBet',
    bookmaker_a_source_url: 'https://www.maxbet.rs/sr/pocetna#/sport/event/23281441',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 160.5,
    threshold_b: 163.5,
    odds_a: 2.02,
    odds_b: 2.02,
    gap: 3.0,
    profit_margin: 0.01,
    middle_profit_margin: 1.02,
    detected_at: ago(5),
    is_active: true,
  },
  {
    // Asian handicap (+OT) middle: meridian rates Olympiacos as -3.5 favourite,
    // mozzart rates them as -5.5. Backing meridian "Home -3.5" + mozzart
    // "Away +5.5" wins outright if Olympiacos wins by exactly 4 or 5.
    id: 12,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'home_handicap_ot',
    player_name: null,
    bookmaker_a_id: 'meridian',
    bookmaker_a_name: 'Meridian',
    bookmaker_b_id: 'mozzart',
    bookmaker_b_name: 'Mozzart',
    threshold_a: 3.5,
    threshold_b: 5.5,
    odds_a: 1.85,
    odds_b: 1.88,
    gap: 2.0,
    profit_margin: 0.0027,
    middle_profit_margin: 0.9457,
    detected_at: ago(2),
    is_active: true,
  },
];

export const mockUnresolvedOdds: UnresolvedOdds[] = [
  {
    id: 1,
    bookmaker_id: 'admiralbet',
    bookmaker_name: 'AdmiralBet',
    raw_league_id: 'AdmiralBet ABA Liga',
    league_id: 'aba_liga',
    league_name: 'ABA League',
    sport: 'basketball',
    market_type: 'player_points',
    player_name: 'P. Nikolic',
    raw_team_name: 'Borac Cacak',
    normalized_team_name: 'Borac Cacak',
    start_time: hours(1),
    threshold: 10.5,
    over_odds: 1.8,
    under_odds: 2.0,
    reason_code: 'no_canonical_matchup_for_team_at_slot',
    candidate_count: 0,
    candidate_matchups: [],
    available_matchups_same_slot: ['Dubai vs Budućnost', 'Ilirija vs FMP'],
    scraped_at: ago(2),
  },
  {
    id: 2,
    bookmaker_id: 'merkurxtip',
    bookmaker_name: 'MERKUR X TIP',
    raw_league_id: 'BBL',
    league_id: 'bbl',
    league_name: null,
    sport: 'basketball',
    market_type: 'player_points',
    player_name: 'Y. Silva',
    raw_team_name: 'BC Dubai',
    normalized_team_name: 'BC Dubai',
    start_time: hours(2),
    threshold: 12.5,
    over_odds: 1.75,
    under_odds: 2.05,
    reason_code: 'no_canonical_matchup_for_team_at_slot',
    candidate_count: 0,
    candidate_matchups: [],
    available_matchups_same_slot: [],
    scraped_at: ago(2),
  },
  {
    id: 3,
    bookmaker_id: 'maxbet',
    bookmaker_name: 'MaxBet',
    raw_league_id: 'ABA Liga',
    league_id: 'aba_liga',
    league_name: 'ABA League',
    sport: 'basketball',
    market_type: 'player_points',
    player_name: 'S. Ilic',
    raw_team_name: 'Borac',
    normalized_team_name: 'Borac',
    start_time: hours(3),
    threshold: 9.5,
    over_odds: 1.9,
    under_odds: 1.9,
    reason_code: 'ambiguous_multiple_matchups_for_team_at_slot',
    candidate_count: 2,
    candidate_matchups: ['Borac Mozzart vs Budućnost', 'FMP vs Borac Mozzart'],
    available_matchups_same_slot: ['Borac Mozzart vs Budućnost', 'FMP vs Borac Mozzart'],
    scraped_at: ago(2),
  },
];

export const mockTeamReviewCases: TeamReviewCase[] = [
  {
    id: 101,
    bookmaker_id: 'meridian',
    bookmaker_name: 'Meridian',
    raw_league_id: 'NBL',
    normalized_raw_league_id: 'nbl',
    sport: 'basketball',
    scope_league_id: 'bulgaria_nbl',
    scope_league_name: 'Bulgaria NBL',
    raw_team_name: 'Rilski Sport.',
    normalized_raw_team_name: 'rilski sport',
    suggested_team_id: 101,
    suggested_team_name: 'Rilski Sportist',
    start_time: hours(2.5),
    review_kind: 'alias_suggestion',
    reason_code: 'candidate_team_match_same_start_time',
    confidence: 'high',
    similarity_score: 92,
    candidate_teams: [
      { team_id: 101, team_name: 'Rilski Sportist', score: 92, matched_alias: null },
      { team_id: 102, team_name: 'Levski Sofia', score: 64, matched_alias: null },
    ],
    matched_counterpart_team: 'Levski Sofia',
    canonical_home_team: 'Rilski Sportist',
    canonical_away_team: 'Levski Sofia',
    evidence: [
      'Exact start time: same as Rilski Sportist vs Levski Sofia',
      'Candidate team: Rilski Sportist',
      'Similarity score: 92',
    ],
    status: 'pending',
    scraped_at: ago(2),
  },
  {
    id: 102,
    bookmaker_id: 'mozzart',
    bookmaker_name: 'Mozzart',
    raw_league_id: 'ABA Liga',
    normalized_raw_league_id: 'aba liga',
    sport: 'basketball',
    scope_league_id: 'aba_liga',
    scope_league_name: 'ABA League',
    raw_team_name: 'Buducnost VOLI',
    normalized_raw_team_name: 'buducnost voli',
    suggested_team_id: 102,
    suggested_team_name: 'Budućnost',
    start_time: hours(1.5),
    review_kind: 'candidate_search',
    reason_code: 'candidate_team_match_same_start_time',
    confidence: 'medium',
    similarity_score: 84,
    candidate_teams: [
      { team_id: 102, team_name: 'Budućnost', score: 84, matched_alias: null },
      { team_id: 103, team_name: 'Dubai', score: 63, matched_alias: null },
      { team_id: 104, team_name: 'Cedevita Olimpija', score: 58, matched_alias: null },
    ],
    matched_counterpart_team: 'Dubai',
    canonical_home_team: 'Dubai',
    canonical_away_team: 'Budućnost',
    evidence: [
      'Exact start time: same as Dubai vs Budućnost',
      'Candidate team: Budućnost',
      'Similarity score: 84',
    ],
    status: 'pending',
    scraped_at: ago(3),
  },
  {
    id: 103,
    bookmaker_id: 'maxbet',
    bookmaker_name: 'MaxBet',
    raw_league_id: 'A1',
    normalized_raw_league_id: 'a1',
    sport: 'basketball',
    scope_league_id: 'greece_a1',
    scope_league_name: 'Greece A1',
    raw_team_name: 'Panathinaikos AKTOR',
    normalized_raw_team_name: 'panathinaikos aktor',
    suggested_team_id: 105,
    suggested_team_name: 'Panathinaikos',
    start_time: hours(5),
    review_kind: 'auto_alias_suggestion',
    reason_code: 'candidate_team_match_same_start_time',
    confidence: 'high',
    similarity_score: 89,
    candidate_teams: [
      { team_id: 105, team_name: 'Panathinaikos', score: 89, matched_alias: null },
    ],
    matched_counterpart_team: 'Olympiacos',
    canonical_home_team: 'Panathinaikos',
    canonical_away_team: 'Olympiacos',
    evidence: [
      'Exact kickoff and counterpart team matched Panathinaikos vs Olympiacos',
      'Anchored alias already matched this canonical event cleanly',
      'Similarity score: 89',
    ],
    status: 'approved',
    scraped_at: ago(10),
  },
];

export const mockEventReviewCases: EventReviewCase[] = [
  {
    id: 201,
    fingerprint: 'basketball:partizan-zvezda:2030-01-01:v1',
    sport: 'basketball',
    start_time: hours(3.25),
    primary_match_id: 'match-2',
    candidate_resolved_event_id: null,
    candidate_match_ids: ['match-2', 'event-candidate-meridian-1'],
    reason_code: 'candidate_event_equivalence',
    confidence: 0.88,
    method: 'heuristic',
    source_bookmaker_ids: ['mozzart', 'meridian'],
    source_league_labels: ['EuroLeague', 'EuroLeague - Main'],
    evidence: [
      'Exact start time matched across both source feeds',
      'Team pair matched with home/away reversed',
      'League labels are compatible after normalization',
    ],
    metadata: { orientation: 'reversed' },
    status: 'pending',
    resolved_event_id: null,
    primary_home_team: 'Fenerbahce',
    primary_away_team: 'Partizan',
    primary_league_name: 'EuroLeague',
    variants: [
      {
        match_id: 'match-2',
        bookmaker_id: 'mozzart',
        bookmaker_name: 'Mozzart',
        league_id: 'euroleague',
        league_name: 'EuroLeague',
        home_team: 'Fenerbahce',
        away_team: 'Partizan',
        start_time: hours(3.25),
        source_url: 'https://mozzart.example/events/partizan',
        source_league_id: 'el',
        source_league_name: 'EuroLeague',
        source_home_team: 'Fenerbahce',
        source_away_team: 'Partizan',
        source_start_time: hours(3.25),
        orientation: 'as_listed',
        confidence: 0.94,
        evidence: ['Canonical match already exists for Mozzart'],
      },
      {
        match_id: 'event-candidate-meridian-1',
        bookmaker_id: 'meridian',
        bookmaker_name: 'Meridian',
        league_id: 'euroleague',
        league_name: 'EuroLeague',
        home_team: 'Partizan',
        away_team: 'Fenerbahce',
        start_time: hours(3.25),
        source_url: 'https://meridian.example/events/partizan',
        source_league_id: 'el-main',
        source_league_name: 'EuroLeague - Main',
        source_home_team: 'Partizan',
        source_away_team: 'Fenerbahce',
        source_start_time: hours(3.25),
        orientation: 'reversed',
        confidence: 0.86,
        evidence: ['Reversed home/away but both canonical teams match'],
      },
    ],
    created_at: ago(12),
    updated_at: ago(6),
    accepted_at: null,
    declined_at: null,
  },
  {
    id: 202,
    fingerprint: 'basketball:mega-buducnost:2030-01-01:v1',
    sport: 'basketball',
    start_time: hours(1.5),
    primary_match_id: 'match-4',
    candidate_resolved_event_id: 'evt_mock_mega_buducnost',
    candidate_match_ids: ['match-4'],
    reason_code: 'manual_event_equivalence',
    confidence: 0.97,
    method: 'manual_review',
    source_bookmaker_ids: ['maxbet', 'mozzart'],
    source_league_labels: ['ABA League'],
    evidence: ['Accepted by operator from event review'],
    metadata: {},
    status: 'accepted',
    resolved_event_id: 'evt_mock_mega_buducnost',
    primary_home_team: 'Mega MIS',
    primary_away_team: 'Budućnost',
    primary_league_name: 'ABA League',
    variants: [
      {
        match_id: 'match-4',
        bookmaker_id: 'maxbet',
        bookmaker_name: 'MaxBet',
        league_id: 'aba-league',
        league_name: 'ABA League',
        home_team: 'Mega MIS',
        away_team: 'Budućnost',
        start_time: hours(1.5),
        source_url: 'https://maxbet.example/events/mega',
        source_league_id: 'aba',
        source_league_name: 'ABA League',
        source_home_team: 'Mega MIS',
        source_away_team: 'Budućnost',
        source_start_time: hours(1.5),
        orientation: 'as_listed',
        confidence: 0.97,
        evidence: ['Operator accepted this source event'],
      },
      {
        match_id: 'match-4',
        bookmaker_id: 'mozzart',
        bookmaker_name: 'Mozzart',
        league_id: 'aba-league',
        league_name: 'ABA League',
        home_team: 'Mega MIS',
        away_team: 'Budućnost',
        start_time: hours(1.5),
        source_url: 'https://mozzart.example/events/mega',
        source_league_id: 'aba',
        source_league_name: 'ABA Liga',
        source_home_team: 'Mega Soccerbet',
        source_away_team: 'Buducnost VOLI',
        source_start_time: hours(1.5),
        orientation: 'as_listed',
        confidence: 0.96,
        evidence: ['Operator accepted this source event'],
      },
    ],
    created_at: ago(80),
    updated_at: ago(40),
    accepted_at: ago(40),
    declined_at: null,
  },
  {
    id: 203,
    fingerprint: 'basketball:barcelona-zvezda:2030-01-01:v1',
    sport: 'basketball',
    start_time: hours(5),
    primary_match_id: 'match-3',
    candidate_resolved_event_id: null,
    candidate_match_ids: ['match-3'],
    reason_code: 'weak_event_equivalence',
    confidence: 0.52,
    method: 'heuristic',
    source_bookmaker_ids: ['maxbet', 'meridian'],
    source_league_labels: ['EuroLeague', 'Club Friendly'],
    evidence: ['League labels conflicted despite similar team names'],
    metadata: {},
    status: 'declined',
    resolved_event_id: null,
    primary_home_team: 'Barcelona',
    primary_away_team: 'Crvena Zvezda',
    primary_league_name: 'EuroLeague',
    variants: [
      {
        match_id: 'match-3',
        bookmaker_id: 'maxbet',
        bookmaker_name: 'MaxBet',
        league_id: 'euroleague',
        league_name: 'EuroLeague',
        home_team: 'Barcelona',
        away_team: 'Crvena Zvezda',
        start_time: hours(5),
        source_url: 'https://maxbet.example/events/barcelona',
        source_league_id: 'el',
        source_league_name: 'EuroLeague',
        source_home_team: 'Barcelona',
        source_away_team: 'Crvena Zvezda',
        source_start_time: hours(5),
        orientation: 'as_listed',
        confidence: 0.52,
        evidence: ['Similar kickoff only'],
      },
    ],
    created_at: ago(120),
    updated_at: ago(30),
    accepted_at: null,
    declined_at: ago(30),
  },
];

export const mockCanonicalTeams: CanonicalTeam[] = [
  {
    id: 101,
    sport: 'basketball',
    display_name: 'Rilski Sportist',
    aliases: ['Rilski Sportist', 'Rilski'],
    alias_count: 2,
    merged_into_team_id: null,
  },
  {
    id: 102,
    sport: 'basketball',
    display_name: 'Budućnost',
    aliases: ['Budućnost', 'Buducnost VOLI'],
    alias_count: 2,
    merged_into_team_id: null,
  },
  {
    id: 103,
    sport: 'basketball',
    display_name: 'Dubai',
    aliases: ['Dubai', 'BC Dubai'],
    alias_count: 2,
    merged_into_team_id: null,
  },
  {
    id: 104,
    sport: 'basketball',
    display_name: 'Cedevita Olimpija',
    aliases: ['Cedevita Olimpija', 'Olimpija Ljubljana'],
    alias_count: 2,
    merged_into_team_id: null,
  },
  {
    id: 105,
    sport: 'basketball',
    display_name: 'Panathinaikos',
    aliases: ['Panathinaikos', 'Panathinaikos AKTOR'],
    alias_count: 2,
    merged_into_team_id: null,
  },
  {
    id: 106,
    sport: 'basketball',
    display_name: 'Baskonia',
    aliases: ['Baskonia', 'Baskonia Gasteiz', 'Saski Baskonia'],
    alias_count: 3,
    merged_into_team_id: null,
  },
];

export const mockSystemStatus: SystemStatus = {
  status: 'ok',
  last_scrape_at: ago(2),
  last_scrape: ago(2),
  total_matches: 6,
  total_odds: mockOddsOffers.length,
  total_opportunities: mockOpportunities.length,
  active_bookmakers: 12,
  scheduler_running: true,
  scan: {
    in_progress: true,
    phase: 'scraping',
    started_at: ago(0),
    total_tasks: 13,
    completed_tasks: 4,
    failed_tasks: 1,
    active_tasks: 8,
  },
  bookmaker_status: [
    { id: 'mozzart', name: 'Mozzart', last_scrape: ago(2), is_active: true },
    { id: 'meridian', name: 'Meridian', last_scrape: ago(3), is_active: true },
    { id: 'maxbet', name: 'MaxBet', last_scrape: ago(4), is_active: true },
    { id: 'balkanbet', name: 'BalkanBet', last_scrape: ago(3), is_active: true },
    { id: 'oktagonbet', name: 'OktagonBet', last_scrape: ago(2), is_active: true },
    { id: 'merkurxtip', name: 'MERKUR X TIP', last_scrape: ago(2), is_active: true },
    { id: 'soccerbet', name: 'SoccerBet', last_scrape: ago(5), is_active: true },
    { id: 'superbet', name: 'Superbet', last_scrape: ago(6), is_active: true },
    { id: 'betole', name: 'BetOle', last_scrape: ago(4), is_active: true },
    { id: '365', name: '365', last_scrape: ago(1), is_active: true },
    { id: 'pinnbet', name: 'PinnBet', last_scrape: ago(2), is_active: true },
    { id: 'volcanobet', name: 'VolcanoBet', last_scrape: ago(4), is_active: true },
  ],
};

export const mockScrapeSettings: ScrapeSettingsResponse = {
  applied: {
    enabled_bookmakers: mockSystemStatus.bookmaker_status?.map((item) => item.id) ?? [],
    enabled_sports: ['basketball', 'football', 'tennis'],
    scrape_market_scope: 'all',
    analysis_markets: ['all'],
    scrape_lookahead_hours: 24,
    scrape_interval_minutes: 10,
    max_middle_opportunities_per_market: 10,
    rate_limit_per_second: 1,
    meridian_rate_limit_per_second: 2,
    soccerbet_detail_mode: 'partial',
    merkurxtip_detail_mode: 'partial',
    pinnbet_detail_mode: 'partial',
    notification_gap_threshold: 1.5,
    persist_inapp_notifications: false,
  },
  defaults: {
    enabled_bookmakers: mockSystemStatus.bookmaker_status?.map((item) => item.id) ?? [],
    enabled_sports: ['basketball', 'football', 'tennis'],
    scrape_market_scope: 'all',
    analysis_markets: ['all'],
    scrape_lookahead_hours: 24,
    scrape_interval_minutes: 10,
    max_middle_opportunities_per_market: 10,
    rate_limit_per_second: 1,
    meridian_rate_limit_per_second: 2,
    soccerbet_detail_mode: 'partial',
    merkurxtip_detail_mode: 'partial',
    pinnbet_detail_mode: 'partial',
    notification_gap_threshold: 1.5,
    persist_inapp_notifications: false,
  },
  pending: null,
  has_pending_changes: false,
  applied_at: ago(2),
  pending_at: null,
  applied_immediately: false,
  options: {
    bookmakers: (mockSystemStatus.bookmaker_status ?? []).map((item) => ({
      id: item.id,
      name: item.name,
      enabled: true,
    })),
    sports: ['basketball', 'football', 'tennis'],
    market_scopes: ['all', 'player_props'],
    analysis_market_options: [
      { token: 'basketball:player_*', label: 'Basketball player props', sport: 'basketball' },
      { token: 'basketball:home_handicap_ot', label: 'Basketball handicap OT', sport: 'basketball' },
      { token: 'basketball:game_total', label: 'Basketball totals', sport: 'basketball' },
      { token: 'basketball:game_total_ot', label: 'Basketball totals OT', sport: 'basketball' },
      { token: 'football:football_total_goals', label: 'Football goals/totals', sport: 'football' },
      { token: 'football:football_result', label: 'Football result', sport: 'football' },
      { token: 'football:football_double_chance', label: 'Football double chance', sport: 'football' },
      {
        token: 'football:football_result_double_chance',
        label: 'Football result + double chance',
        sport: 'football',
      },
      { token: 'tennis:tennis_match_winner', label: 'Tennis match winner', sport: 'tennis' },
      { token: 'tennis:match_winner', label: 'Tennis match winner (generic)', sport: 'tennis' },
    ],
    detail_modes: ['partial', 'full'],
    scrape_interval_minutes_min: 1,
    scrape_interval_minutes_max: 1440,
    scrape_lookahead_hours_min: 0,
    scrape_lookahead_hours_max: 87600,
    max_middle_opportunities_per_market_min: 1,
    max_middle_opportunities_per_market_max: 1000,
    rate_limit_per_second_min: 0,
    rate_limit_per_second_max: 20,
  },
};

export const mockTelegramSettings: TelegramSettingsResponse = {
  token_configured: false,
  api_base_url: 'https://api.telegram.org',
  profiles: [
    {
      id: 1,
      label: 'Main chat',
      chat_id: '123456789',
      enabled: true,
      min_gap: 1.5,
      min_roi_percent: 5,
      min_middle_ev_percent: 1,
      bookmaker_ids: ['mozzart', 'meridian', 'maxbet'],
      rate_limited_until: null,
      last_delivery_error: null,
      created_at: ago(30),
      updated_at: ago(12),
    },
  ],
};
