import type { League, Match, OddsOffer, Discrepancy, SystemStatus } from './types';

const now = new Date();
const hours = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();
const ago = (min: number) => new Date(now.getTime() - min * 60000).toISOString();

export const mockLeagues: League[] = [
  { id: 'euroleague', name: 'EuroLeague', sport: 'basketball', country: null, is_active: true },
  { id: 'aba-league', name: 'ABA League', sport: 'basketball', country: 'Serbia', is_active: true },
  { id: 'kls', name: 'KLS', sport: 'basketball', country: 'Serbia', is_active: true },
];

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    league_id: 'euroleague',
    league_name: 'EuroLeague',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    start_time: hours(2),
    status: 'upcoming',
  },
  {
    id: 'match-2',
    league_id: 'euroleague',
    league_name: 'EuroLeague',
    home_team: 'Fenerbahce',
    away_team: 'Partizan',
    start_time: hours(3),
    status: 'upcoming',
  },
  {
    id: 'match-3',
    league_id: 'euroleague',
    league_name: 'EuroLeague',
    home_team: 'Barcelona',
    away_team: 'Crvena Zvezda',
    start_time: hours(5),
    status: 'upcoming',
  },
  {
    id: 'match-4',
    league_id: 'aba-league',
    league_name: 'ABA League',
    home_team: 'Mega MIS',
    away_team: 'Budućnost',
    start_time: hours(1),
    status: 'upcoming',
  },
  {
    id: 'match-5',
    league_id: 'aba-league',
    league_name: 'ABA League',
    home_team: 'Crvena Zvezda',
    away_team: 'Cedevita Olimpija',
    start_time: hours(4),
    status: 'upcoming',
  },
  {
    id: 'match-6',
    league_id: 'kls',
    league_name: 'KLS',
    home_team: 'FMP',
    away_team: 'Vojvodina',
    start_time: hours(1.5),
    status: 'upcoming',
  },
];

export const mockOddsOffers: OddsOffer[] = [
  // Match 1: Olympiacos vs Real Madrid
  { id: 1, match_id: 'match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 18.5, over_odds: 1.85, under_odds: 1.95, scraped_at: ago(5) },
  { id: 2, match_id: 'match-1', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 20.5, over_odds: 1.75, under_odds: 1.90, scraped_at: ago(3) },
  { id: 3, match_id: 'match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'player_points', player_name: 'Sasha Vezenkov', threshold: 19.5, over_odds: 1.80, under_odds: 1.88, scraped_at: ago(4) },
  { id: 4, match_id: 'match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 155.5, over_odds: 1.80, under_odds: 2.00, scraped_at: ago(5) },
  { id: 5, match_id: 'match-1', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total', player_name: null, threshold: 158.5, over_odds: 1.90, under_odds: 1.85, scraped_at: ago(3) },
  { id: 6, match_id: 'match-1', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'game_total', player_name: null, threshold: 156.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(4) },
  { id: 7, match_id: 'match-1', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Facundo Campazzo', threshold: 14.5, over_odds: 1.90, under_odds: 1.88, scraped_at: ago(5) },
  { id: 8, match_id: 'match-1', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Facundo Campazzo', threshold: 15.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(3) },

  // Match 2: Fenerbahce vs Partizan
  { id: 9, match_id: 'match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 15.5, over_odds: 1.88, under_odds: 1.92, scraped_at: ago(5) },
  { id: 10, match_id: 'match-2', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 17.5, over_odds: 1.75, under_odds: 2.05, scraped_at: ago(4) },
  { id: 11, match_id: 'match-2', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Nigel Hayes-Davis', threshold: 16.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(3) },
  { id: 12, match_id: 'match-2', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 160.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(5) },
  { id: 13, match_id: 'match-2', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'game_total', player_name: null, threshold: 162.5, over_odds: 1.88, under_odds: 1.90, scraped_at: ago(4) },

  // Match 3: Barcelona vs Crvena Zvezda
  { id: 14, match_id: 'match-3', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Nikola Kalinić', threshold: 12.5, over_odds: 1.92, under_odds: 1.85, scraped_at: ago(6) },
  { id: 15, match_id: 'match-3', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Nikola Kalinić', threshold: 14.5, over_odds: 1.78, under_odds: 2.00, scraped_at: ago(2) },
  { id: 16, match_id: 'match-3', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'player_points', player_name: 'Nikola Kalinić', threshold: 13.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(4) },
  { id: 17, match_id: 'match-3', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 162.5, over_odds: 1.78, under_odds: 2.02, scraped_at: ago(6) },
  { id: 18, match_id: 'match-3', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total', player_name: null, threshold: 164.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(2) },

  // Match 4: Mega MIS vs Budućnost
  { id: 19, match_id: 'match-4', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Nikola Đurišić', threshold: 16.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(8) },
  { id: 20, match_id: 'match-4', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'player_points', player_name: 'Nikola Đurišić', threshold: 18.5, over_odds: 1.78, under_odds: 2.00, scraped_at: ago(6) },
  { id: 21, match_id: 'match-4', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 165.5, over_odds: 1.85, under_odds: 1.92, scraped_at: ago(8) },
  { id: 22, match_id: 'match-4', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'game_total', player_name: null, threshold: 168.5, over_odds: 1.90, under_odds: 1.88, scraped_at: ago(6) },

  // Match 5: Crvena Zvezda vs Cedevita Olimpija
  { id: 23, match_id: 'match-5', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'player_points', player_name: 'Filip Petrušev', threshold: 17.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(10) },
  { id: 24, match_id: 'match-5', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'player_points', player_name: 'Filip Petrušev', threshold: 19.5, over_odds: 1.75, under_odds: 2.05, scraped_at: ago(7) },
  { id: 25, match_id: 'match-5', bookmaker_id: 'maxbet', bookmaker_name: 'MaxBet', market_type: 'player_points', player_name: 'Filip Petrušev', threshold: 18.5, over_odds: 1.80, under_odds: 1.98, scraped_at: ago(5) },

  // Match 6: FMP vs Vojvodina
  { id: 26, match_id: 'match-6', bookmaker_id: 'mozzart', bookmaker_name: 'Mozzart', market_type: 'game_total', player_name: null, threshold: 158.5, over_odds: 1.88, under_odds: 1.90, scraped_at: ago(12) },
  { id: 27, match_id: 'match-6', bookmaker_id: 'meridian', bookmaker_name: 'Meridian', market_type: 'game_total', player_name: null, threshold: 161.5, over_odds: 1.82, under_odds: 1.95, scraped_at: ago(8) },
];

export const mockDiscrepancies: Discrepancy[] = [
  {
    id: 1,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Sasha Vezenkov',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 18.5,
    threshold_b: 20.5,
    odds_a: 1.85,
    odds_b: 1.90,
    gap: 2.0,
    profit_margin: 0.032,
    middle_profit_margin: 0.8747,
    detected_at: ago(5),
    is_active: true,
  },
  {
    id: 2,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'maxbet',
    bookmaker_a_name: 'MaxBet',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 155.5,
    threshold_b: 158.5,
    odds_a: 1.80,
    odds_b: 1.85,
    gap: 3.0,
    profit_margin: 0.028,
    middle_profit_margin: 0.8247,
    detected_at: ago(4),
    is_active: true,
  },
  {
    id: 3,
    match_id: 'match-2',
    home_team: 'Fenerbahce',
    away_team: 'Partizan',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Nigel Hayes-Davis',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'maxbet',
    bookmaker_b_name: 'MaxBet',
    threshold_a: 15.5,
    threshold_b: 17.5,
    odds_a: 1.88,
    odds_b: 2.05,
    gap: 2.0,
    profit_margin: 0.041,
    middle_profit_margin: 0.9613,
    detected_at: ago(5),
    is_active: true,
  },
  {
    id: 4,
    match_id: 'match-3',
    home_team: 'Barcelona',
    away_team: 'Crvena Zvezda',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Nikola Kalinić',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 12.5,
    threshold_b: 14.5,
    odds_a: 1.92,
    odds_b: 2.00,
    gap: 2.0,
    profit_margin: 0.035,
    middle_profit_margin: 0.9592,
    detected_at: ago(6),
    is_active: true,
  },
  {
    id: 5,
    match_id: 'match-4',
    home_team: 'Mega MIS',
    away_team: 'Budućnost',
    league_name: 'ABA League',
    market_type: 'player_points',
    player_name: 'Nikola Đurišić',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'maxbet',
    bookmaker_b_name: 'MaxBet',
    threshold_a: 16.5,
    threshold_b: 18.5,
    odds_a: 1.85,
    odds_b: 2.00,
    gap: 2.0,
    profit_margin: 0.024,
    middle_profit_margin: 0.9221,
    detected_at: ago(8),
    is_active: true,
  },
  {
    id: 6,
    match_id: 'match-4',
    home_team: 'Mega MIS',
    away_team: 'Budućnost',
    league_name: 'ABA League',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'maxbet',
    bookmaker_b_name: 'MaxBet',
    threshold_a: 165.5,
    threshold_b: 168.5,
    odds_a: 1.85,
    odds_b: 1.88,
    gap: 3.0,
    profit_margin: 0.018,
    middle_profit_margin: 0.8649,
    detected_at: ago(8),
    is_active: true,
  },
  {
    id: 7,
    match_id: 'match-5',
    home_team: 'Crvena Zvezda',
    away_team: 'Cedevita Olimpija',
    league_name: 'ABA League',
    market_type: 'player_points',
    player_name: 'Filip Petrušev',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 17.5,
    threshold_b: 19.5,
    odds_a: 1.82,
    odds_b: 2.05,
    gap: 2.0,
    profit_margin: 0.038,
    middle_profit_margin: 0.9282,
    detected_at: ago(7),
    is_active: true,
  },
  {
    id: 8,
    match_id: 'match-6',
    home_team: 'FMP',
    away_team: 'Vojvodina',
    league_name: 'KLS',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 158.5,
    threshold_b: 161.5,
    odds_a: 1.88,
    odds_b: 1.95,
    gap: 3.0,
    profit_margin: 0.012,
    middle_profit_margin: 0.8474,
    detected_at: ago(12),
    is_active: true,
  },
  {
    id: 9,
    match_id: 'match-1',
    home_team: 'Olympiacos',
    away_team: 'Real Madrid',
    league_name: 'EuroLeague',
    market_type: 'player_points',
    player_name: 'Facundo Campazzo',
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 14.5,
    threshold_b: 15.5,
    odds_a: 1.90,
    odds_b: 1.95,
    gap: 1.0,
    profit_margin: 0.016,
    middle_profit_margin: 0.9247,
    detected_at: ago(5),
    is_active: true,
  },
  {
    id: 10,
    match_id: 'match-3',
    home_team: 'Barcelona',
    away_team: 'Crvena Zvezda',
    league_name: 'EuroLeague',
    market_type: 'game_total',
    player_name: null,
    bookmaker_a_id: 'mozzart',
    bookmaker_a_name: 'Mozzart',
    bookmaker_b_id: 'meridian',
    bookmaker_b_name: 'Meridian',
    threshold_a: 162.5,
    threshold_b: 164.5,
    odds_a: 1.78,
    odds_b: 1.92,
    gap: 2.0,
    profit_margin: 0.021,
    middle_profit_margin: 0.9144,
    detected_at: ago(6),
    is_active: true,
  },
];

export const mockSystemStatus: SystemStatus = {
  status: 'ok',
  last_scrape_at: ago(2),
  last_scrape: ago(2),
  total_matches: 6,
  total_odds: mockOddsOffers.length,
  total_discrepancies: 10,
  active_bookmakers: 3,
  scheduler_running: true,
  scan: {
    in_progress: true,
    phase: 'scraping',
    started_at: ago(0),
    total_tasks: 8,
    completed_tasks: 3,
    failed_tasks: 1,
    active_tasks: 4,
  },
  active_discrepancies: 10,
  bookmaker_status: [
    { id: 'mozzart', name: 'Mozzart', last_scrape: ago(2), is_active: true },
    { id: 'meridian', name: 'Meridian', last_scrape: ago(3), is_active: true },
    { id: 'maxbet', name: 'MaxBet', last_scrape: ago(4), is_active: true },
  ],
};
