from __future__ import annotations


_BASKETBALL_CANONICAL_ALIASES: dict[str, str] = {
    "olympiacos": "Olympiacos",
    "olympiakos": "Olympiacos",
    "real madrid": "Real Madrid",
    "fenerbahce": "Fenerbahce",
    "fenerbahce istanbul": "Fenerbahce",
    "fc barcelona": "FC Barcelona",
    "barcelona": "FC Barcelona",
    "partizan": "Partizan",
    "crvena zvezda": "Crvena Zvezda",
    "crv zvezda": "Crvena Zvezda",
    "kk crvena zvezda": "Crvena Zvezda",
    "red star": "Crvena Zvezda",
    "panathinaikos": "Panathinaikos",
    "anadolu efes": "Anadolu Efes",
    "efes": "Anadolu Efes",
    "bayern munich": "Bayern Munich",
    "bayern": "Bayern Munich",
    "maccabi tel aviv": "Maccabi Tel Aviv",
    "maccabi": "Maccabi Tel Aviv",
    "hapoel tel aviv": "Hapoel Tel-Aviv",
    "hapoel tel-aviv": "Hapoel Tel-Aviv",
    "asvel": "Asvel",
    "asvel lyon-villeurbanne": "Asvel",
    "lyon-villeurb.": "Asvel",
    "lyon-villeurbanne": "Asvel",
    "universitatea cluj": "Universitatea Cluj",
    "cluj napoc": "Universitatea Cluj",
    "cluj napoca": "Universitatea Cluj",
    "buducnost": "Buducnost",
    "buducnost voli": "Buducnost",
    "kk bosna": "KK Bosna",
    "ostrow": "Ostrow Wielkopolski",
    "atlanta": "Atlanta Hawks",
    "atlanta hawks": "Atlanta Hawks",
    "boston": "Boston Celtics",
    "boston celtics": "Boston Celtics",
    "brooklyn": "Brooklyn Nets",
    "brooklyn nets": "Brooklyn Nets",
    "charlotte": "Charlotte Hornets",
    "charlotte hornets": "Charlotte Hornets",
    "chicago": "Chicago Bulls",
    "chicago bulls": "Chicago Bulls",
    "cleveland": "Cleveland Cavaliers",
    "cleveland cavaliers": "Cleveland Cavaliers",
    "dallas": "Dallas Mavericks",
    "dallas mavericks": "Dallas Mavericks",
    "denver": "Denver Nuggets",
    "denver nuggets": "Denver Nuggets",
    "detroit": "Detroit Pistons",
    "detroit pistons": "Detroit Pistons",
    "golden state": "Golden State Warriors",
    "golden state warriors": "Golden State Warriors",
    "houston": "Houston Rockets",
    "houston rockets": "Houston Rockets",
    "indiana": "Indiana Pacers",
    "indiana pacers": "Indiana Pacers",
    "la clippers": "Los Angeles Clippers",
    "los angeles clippers": "Los Angeles Clippers",
    "la lakers": "Los Angeles Lakers",
    "los angeles lakers": "Los Angeles Lakers",
    "memphis": "Memphis Grizzlies",
    "memphis grizzlies": "Memphis Grizzlies",
    "miami": "Miami Heat",
    "miami heat": "Miami Heat",
    "milwaukee": "Milwaukee Bucks",
    "milwaukee bucks": "Milwaukee Bucks",
    "minnesota": "Minnesota Timberwolves",
    "minnesota timberwolves": "Minnesota Timberwolves",
    "new orleans": "New Orleans Pelicans",
    "new orleans pelicans": "New Orleans Pelicans",
    "new york": "New York Knicks",
    "new york knicks": "New York Knicks",
    "okc": "Oklahoma City Thunder",
    "oklahoma city": "Oklahoma City Thunder",
    "oklahoma city thunder": "Oklahoma City Thunder",
    "orlando": "Orlando Magic",
    "orlando magic": "Orlando Magic",
    "philadelphia": "Philadelphia 76ers",
    "philadelphia 76ers": "Philadelphia 76ers",
    "phoenix": "Phoenix Suns",
    "phoenix suns": "Phoenix Suns",
    "portland": "Portland Trail Blazers",
    "portland trail blazers": "Portland Trail Blazers",
    "sacramento": "Sacramento Kings",
    "sacramento kings": "Sacramento Kings",
    "san antonio": "San Antonio Spurs",
    "san antonio spurs": "San Antonio Spurs",
    "toronto": "Toronto Raptors",
    "toronto raptors": "Toronto Raptors",
    "utah": "Utah Jazz",
    "utah jazz": "Utah Jazz",
    "washington": "Washington Wizards",
    "washington wizards": "Washington Wizards",
    "obras sanitarias": "Obras Sanitarias",
    "instituto de cordoba": "Instituto de Cordoba",
    "inst de cordoba": "Instituto de Cordoba",
    "uu korihait uusikaupunki": "Korihait Uusikaupunki",
    "uu korihait": "Korihait Uusikaupunki",
    "uu-korihait": "Korihait Uusikaupunki",
    "korihait": "Korihait Uusikaupunki",
    "korihait u.": "Korihait Uusikaupunki",
    "salon vilpas": "Salon Vilpas",
    "salon vilpas vikings": "Salon Vilpas",
    "capitanes de arecibo": "Capitanes de Arecibo",
    "capitanes de a": "Capitanes de Arecibo",
    "rilski sportist": "Rilski Sportist",
    "levski sofia": "Levski Sofia",
    "zielona gora": "Zielona Gora",
}


SPORT_ALIAS_SEEDS: dict[str, dict[str, str]] = {
    "basketball": _BASKETBALL_CANONICAL_ALIASES,
}
